#!/bin/bash

# redirect all output to stderr
{
  INPUT_TREE="${1?<input> required}"
  DATA_TREE="${HOLOLENS_DATA:-${INPUT_TREE}}"
  NPM_RUN_COMMAND="${HOLOLENS_NPM_RUN_COMMAND?hololens.npm-run.command required}"
  NPM_RUN_INSTALL="${HOLOLENS_NPM_RUN_INSTALL:-npm ci}"
  NPM_RUN_ENV="${HOLOLENS_NPM_RUN_ENV:-production}"
  OUTPUT_DIR="${HOLOLENS_NPM_RUN_OUTPUT_DIR}"

  if [ "$(git cat-file -t ${DATA_TREE} 2> /dev/null)" != "tree" ]; then
    echo "hololens.data '${DATA_TREE}' is not a reachable tree"
    exit 1;
  fi


  # set up environment
  echo "Exporting data tree to scratch directory: ${DATA_TREE}"
  git holo lens export-tree "${DATA_TREE}"

  echo "Configuring environment: CI=true"
  export CI="true"

  echo "Configuring environment: NODE_ENV=${NPM_RUN_ENV}"
  export NODE_ENV="${NPM_RUN_ENV}"


  # execute npm install
  echo
  echo "Running: ${NPM_RUN_INSTALL}"
  ${NPM_RUN_INSTALL}
  install_status=$?

  if [ $install_status -ne 0 ]; then
    echo -e "\n${NPM_RUN_INSTALL} failed with exit status ${install_status}"
    exit ${install_status}
  fi


  # fix interpreters
  sed -e "s#\#\!/usr/bin/env node#\#\!$(hab pkg path core/node)/bin/node#" --in-place --follow-symlinks node_modules/.bin/*


  # execute configured command
  echo
  echo "Running: npm run ${NPM_RUN_COMMAND}"
  command_output=$(npm run --silent ${NPM_RUN_COMMAND})
  command_status=$?

  if [ $command_status -ne 0 ]; then
    echo -e "\n${NPM_RUN_COMMAND} failed with exit status ${command_status}"
    exit ${command_status}
  fi

  echo -e "\n${NPM_RUN_COMMAND} completed successfully"


  # add output to git index if OUTPUT_DIR is declared
  if [ -n "${OUTPUT_DIR}" ]; then
    git add "${OUTPUT_DIR}"
  fi

} 1>&2


# output tree hash
if [ -n "${OUTPUT_DIR}" ]; then
  git write-tree --prefix="${OUTPUT_DIR}"
else
  echo "${command_output}"
fi
