#!/bin/bash

# redirect all output to stderr
{
  INPUT_TREE="${1?<input> required}"
  DATA_TREE="${HOLOLENS_DATA?data tree required}"
  NPM_RUN_COMMAND="${HOLOLENS_NPM_RUN_COMMAND?hololens.npm-run.command required}"
  NPM_RUN_INSTALL="${HOLOLENS_NPM_RUN_INSTALL:-npm install --no-audit}"
  NPM_RUN_ENV="${HOLOLENS_NPM_RUN_ENV:-production}"
  OUTPUT_DIR="${HOLOLENS_NPM_RUN_OUTPUT_DIR:-dist}"

  if [ "$(git cat-file -t ${DATA_TREE} 2> /dev/null)" != "tree" ]; then
    echo "hololens.data '${DATA_TREE}' is not a reachable tree"
    exit 1;
  fi

  # set up environment
  git holo lens export-tree "${DATA_TREE}"
  export CI="true"

  # execute npm install
  echo
  echo "Running: ${NPM_RUN_INSTALL}"
  ${NPM_RUN_INSTALL}
  install_status=$?

  if [ $install_status -ne 0 ]; then
    echo -e "\n${NPM_RUN_INSTALL} failed with exit status ${install_status}"
    exit ${install_status}
  fi

  # execute configured command
  echo
  echo "Running: NODE_ENV=\"${NPM_RUN_ENV}\" ${NPM_RUN_COMMAND}"
  NODE_ENV="${NPM_RUN_ENV}" npm run ${NPM_RUN_COMMAND}
  command_status=$?

  if [ $command_status -ne 0 ]; then
    echo -e "\n${NPM_RUN_COMMAND} failed with exit status ${command_status}"
    exit ${command_status}
  fi

  echo -e "\n${NPM_RUN_COMMAND} completed successfully"

  # add output to git index
  git add "${OUTPUT_DIR}"

} 1>&2

# output tree hash
git write-tree --prefix="${OUTPUT_DIR}"
